name: Test IAM Role Comparison in Terraform

on:
  workflow_dispatch:  # Allows manual execution

permissions:
  id-token: write
  contents: read

jobs:
  test-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract AWS IAM Roles from JSON
        working-directory: ./.github
        run: |
          bash ./scripts/extract_iam_role_arns.sh '../Infra/deployment_config.json' 'dev' >> $GITHUB_ENV

      - name: Debug Extracted IAM Roles
        run: |
          echo "Extracted IAM Roles from JSON:"
          echo "DEFAULT_IAM_ROLE_ARN: $DEFAULT_IAM_ROLE_ARN"
          echo "DNS_IAM_ROLE_ARN: $DNS_IAM_ROLE_ARN"

      - name: Configure AWS Credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.DEFAULT_IAM_ROLE_ARN }}
          aws-region: ${{ env.DEFAULT_IAM_ROLE_REGION }}
          role-session-name: devSession

      - name: Debug AWS Caller Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        working-directory: ./Infra/environments/dev
        env:
          TF_VAR_dns_iam_role_arn: ${{ env.DNS_IAM_ROLE_ARN }}
          TF_VAR_default_iam_role_arn: ${{ env.DEFAULT_IAM_ROLE_ARN }}
        run: |
          terraform init
          ls

      - name: Debug Terraform Variables Before Plan
        run: |
          echo "TF_VAR_default_iam_role_arn: $TF_VAR_default_iam_role_arn"
          echo "TF_VAR_dns_iam_role_arn: $TF_VAR_dns_iam_role_arn"

      - name: Terraform Plan
        working-directory: ./Infra/environments/dev
        env:
          TF_VAR_dns_iam_role_arn: ${{ env.DNS_IAM_ROLE_ARN }}
          TF_VAR_default_iam_role_arn: ${{ env.DEFAULT_IAM_ROLE_ARN }}
        run: terraform plan -var-file="deploy_dev.tfvars" -out=tfplan

      - name: Debug Terraform Outputs
        working-directory: ./Infra/environments/dev
        run: terraform output

      - name: Terraform Apply (Dry Run)
        working-directory: ./Infra/environments/dev
        env:
          TF_VAR_dns_iam_role_arn: ${{ env.DNS_IAM_ROLE_ARN }}
          TF_VAR_default_iam_role_arn: ${{ env.DEFAULT_IAM_ROLE_ARN }}
        run: terraform apply -var-file="deploy_dev.tfvars" -auto-approve -parallelism=1

